# S14 A resource has no more than one value of skos:prefLabel per language tag.
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT *
WHERE {
      ?x0 skos:prefLabel ?x1 .
      ?x0 skos:prefLabel ?x2 .
      FILTER (?x1 != ?x2 && lang(?x1) = lang(?x2))
}
