# S19 skos:semanticRelation has rdfs:domain skos:Concept

SELECT DISTINCT *
WHERE {
   ?x0 <http://www.w3.org/2004/02/skos/core#semanticRelation> ?x1 .
   FILTER NOT EXISTS {
      ?x0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> .
   }
}
