# S46-1 skos:exactMatch is disjoint with skos:relatedMatch.
SELECT DISTINCT *
WHERE {
   ?x0 <http://www.w3.org/2004/02/skos/core#exactMatch> ?x1 .
   ?x0 <http://www.w3.org/2004/02/skos/core#relatedMatch> ?x1 .
}

