# All dimension components in a DSD have a unique dimension

PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT * {
  GRAPH ?dsgraph {
    ?ds a qb:DataSet ;
      qb:structure/qb:component ?comp1, ?comp2 .
    FILTER (?comp1 != ?comp2) .
    {
      ?comp1 qb:dimension ?dim1 .
    } UNION {
      ?comp1 qb:componentProperty ?dim1 .
      ?dim1 a qb:DimensionProperty .
    }
    {
      ?comp2 qb:dimension ?dim2 .
    } UNION {
      ?comp2 qb:componentProperty ?dim2 .
      ?dim2 a qb:DimensionProperty .
    }
    FILTER (?dim1 = ?dim2)
  }
}
